package entities;

import common.*;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Server entity. Contains a GUI to help the user interact with the entity and see what is happening internally.
 * Entity responsible for making the pi calculation themselves.
 * @author Filipe Pires (85122) and João Alegria (85048)
 */
public class Server extends javax.swing.JFrame implements MessageProcessor {
    
    private int id=-1;
    
    private SocketServer socketServer;
    private Thread serverThread;
    private int socketStatus;
    
    private List<String> processingRequests;
    private List<String> processedRequests;
    
    /**
     * Creates new form Server.
     * @param args main server host IP address and port.
     */
    public Server(String args[]) {
        this.processingRequests=new ArrayList();
        this.processedRequests=new ArrayList();
        
        initComponents();
        this.setTitle("Server");
        this.warning.setVisible(false);
        this.warning.setForeground(Color.red);
        this.host.setText("localhost");
        this.port.setText(args[0]);
        this.mainServerHost.setText(args[1]);
        this.mainServerPort.setText(args[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        processing = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        processed = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        mainServerHost = new javax.swing.JTextField();
        mainServerPort = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        warning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(663, 296));

        stop.setText("Stop");
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(processing);

        jScrollPane2.setViewportView(processed);

        jLabel1.setText("Main Server:");

        confirm.setText("Confirm");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });

        jLabel2.setText("Server:");

        status.setEditable(false);
        status.setBackground(java.awt.Color.red);
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.setText("Status");
        status.setFocusable(false);

        warning.setText("Warning: invalid input.");

        jLabel3.setText("Requests Received:");

        jLabel4.setText("Processed:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainServerHost, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addGap(154, 154, 154)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(208, 208, 208))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainServerHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(mainServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm)
                    .addComponent(jLabel2)
                    .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop)
                    .addComponent(warning))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        if(this.id>=0){
            try {
                SocketClient socketManager = new SocketClient(this.mainServerHost.getText(), Integer.valueOf(this.mainServerPort.getText()));
                socketManager.send("serverDown-" + this.id);
                socketManager.close();
            } catch (IOException ex) {
//                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_stopMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        if(this.socketServer==null){
            this.socketServer = new SocketServer(Integer.valueOf(this.port.getText()), this);
            this.socketStatus = 0;
            this.serverThread = new Thread(socketServer);
            this.serverThread.start();
            
            while(this.socketStatus == 0) {}
            
            if(this.socketStatus<0) {
                this.warning.setVisible(true);
                this.socketServer = null;
                return;
            }
        }
        if(this.registerServer()){
            this.warning.setVisible(false);
            this.confirm.setEnabled(false);
            this.host.setEnabled(false);
            this.port.setEnabled(false);
            this.mainServerHost.setEnabled(false);
            this.mainServerPort.setEnabled(false);
        }
    }//GEN-LAST:event_confirmMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server(args).setVisible(true);
            }
        });
    }
    
    /**
     * Registers the server in the Tactic manager.
     * @return boolean representing if the action was successful or not.
     */
    public boolean registerServer(){
        try {
            SocketClient socketManager = new SocketClient(this.mainServerHost.getText(), Integer.valueOf(this.mainServerPort.getText()));
            socketManager.send("newServer-localhost-" + Integer.valueOf(this.port.getText()));
            socketManager.close();
            status.setBackground(Color.green);
            return true;
        } catch (IOException ex) {
//            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            status.setBackground(Color.red);
            return false;
        }
    }

    /**
     * Establishes the logic to use when processing incoming messages.
     * @param message String containing the incoming message
     * @return String containing the acknowledge message intended to be returned to the message sender 
     */
    @Override
    public String processMessage(String message) {
        String[] processedMessage = message.split("-");
        switch(processedMessage[0]){
            case "serverId"://serverId-id
                this.id=Integer.valueOf(processedMessage[1]);
                this.setTitle("Server #" + this.id);
                break;
            case "healthcheck":// healthcheck
                break;
            case "request": //request-clientHost-clientPort-request
                SocketClient socketManager = new SocketClient(this.mainServerHost.getText(), Integer.valueOf(this.mainServerPort.getText()));
                try {
                    socketManager.send("newRequest-"+this.id+"-" + processedMessage[3]);
                    socketManager.close();
                    processingRequests.add(processedMessage[3]);
                    updateProcessing();
                    PiCalculation request = new PiCalculation(processedMessage[1], Integer.valueOf(processedMessage[2]),processedMessage[3]);
                    Thread requestProcessing = new Thread(request);
                    requestProcessing.start();
                } catch (IOException ex) {
                    Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                break;

        }
        return "Message processed with success.";
    }

    /**
     * Updates the current server socket status.
     * @param socketStatus int representing the satus of the socket.
     */
    @Override
    public void setSocketStatus(int socketStatus) {
        this.socketStatus = socketStatus;
    }
    
    /**
     * Auxiliary class created to execute the pi calculation themselves. Worker thread created to each client.
     */
    private class PiCalculation implements Runnable{
        
        private String message;
        private String[] processedMessage;
        private final int clientPort;
        private final String clientHost;
        
        public PiCalculation(String clientHost, int clientPort, String message){
            this.message=message;
            String[] tmp=message.replaceAll("\\s+","").split("\\|");
            this.processedMessage = Arrays.copyOfRange(tmp, 1, tmp.length);
            for(String m: this.processedMessage) {
                m = m.trim();
            }
            this.clientHost=clientHost;
            this.clientPort=clientPort;
        }
        
        /**
         * Lifecycle of the pi calculation  worker thread.
         */
        @Override
        public void run() {
            try {
                Thread.sleep(Integer.valueOf(this.processedMessage[3])*1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }

            String reply = "| " +id + " | " + this.processedMessage[0] + " | " + this.processedMessage[1] + " | 02 | " + this.processedMessage[3] + " | 3.1415 |";
            
            SocketClient targetClient = new SocketClient(clientHost, clientPort);
            try {
                targetClient.send(reply);
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
            targetClient.close();
            
            SocketClient socketManager = new SocketClient(mainServerHost.getText(), Integer.valueOf(mainServerPort.getText()));
            try {
                socketManager.send("processedRequest-"+id+"-" + message);
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
            socketManager.close();
            processingRequests.remove(message);
            processedRequests.add(message);
            updateProcessing();
            updateProcessed();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JTextField host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mainServerHost;
    private javax.swing.JTextField mainServerPort;
    private javax.swing.JTextField port;
    private javax.swing.JList<String> processed;
    private javax.swing.JList<String> processing;
    private javax.swing.JTextField status;
    private javax.swing.JButton stop;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

    /**
     * Updates the GUI processing requests list.
     */
    private void updateProcessing(){
        String[] tmp=new String[processingRequests.size()];
        processingRequests.toArray(tmp);
        processing.setListData(tmp);
    }
    
    /**
     * Updates the GUI processed requests list.
     */
    private void updateProcessed(){
        String[] tmp=new String[processedRequests.size()];
        processedRequests.toArray(tmp);
        processed.setListData(tmp);
    }

}
